version: '3'

services:
  # MQTT Broker
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"   # MQTT port
      - "8083:8083"   # MQTT over WebSocket
      - "8084:8084"   # MQTT over WSS
      - "8883:8883"   # MQTT over TLS
      - "18083:18083" # Dashboard
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    environment:
      - EMQX_NAME=emqx
      - EMQX_ALLOW_ANONYMOUS=true
    restart: always
    networks:
      - iot-network

  # InfluxDB Time Series Database
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - ./influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=your_secure_password
      - DOCKER_INFLUXDB_INIT_ORG=your_organization
      - DOCKER_INFLUXDB_INIT_BUCKET=van
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=uWM4SyrMUSRg0WbQFZQVUZ8mmw9n8OIpsj2FDY1Oft05Z6w9HTjgyn6p5ENP79BknWZOz1xUdklnKgULEmDQdQ==
    restart: always
    networks:
      - iot-network

  # Telegraf Data Collection Agent
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
      - emqx
    volumes:
      - ./telegraf/telem.toml:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUX_TOKEN=uWM4SyrMUSRg0WbQFZQVUZ8mmw9n8OIpsj2FDY1Oft05Z6w9HTjgyn6p5ENP79BknWZOz1xUdklnKgULEmDQdQ==
    restart: always
    network_mode: "host"

volumes:
  emqx-data:
  emqx-log:
  influxdb-data:

networks:
  iot-network:
    driver: bridge